### ISSUE TITLE
OOM Problem

### ISSUE THREAD

**Issue by chenhongjin811** [zhuomanliu/PhysFlow#1]
May I ask what is the minimum GPU memory required for this model inference? My 24GB memory device encountered an out of memory error after running

**Comment by zhuomanliu** [comment]
Hi, I've tested on the synthetic dataset. A 24GB GPU is enough for evaluation, but training requires a GPU with larger memory, about 51GB is needed during training for your reference. For the experiments in the paper, we used the A800 GPU.

------
I found a bug where the evaluation process would not terminate properly, resulting in an increase in memory usage. The bug has now been fixed.

**Comment by ZaiyiHu** [comment]
Hi, very interesting work! Thank you for sharing. I would like to ask about the how many hours that experiments may take in the paper by one A800 GPU?

> Hi, I've tested on the synthetic dataset. A 24GB GPU is enough for evaluation, but training requires a GPU with larger memory, about 51GB is needed during training for your reference. For the experiments in the paper, we used the A800 GPU.
> 
> I found a bug where the evaluation process would not terminate properly, resulting in an increase in memory usage. The bug has now been fixed.
